// <auto-generated />
using System;
using HJMH.Tarifarios.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HJMH.Tarifarios.Backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250121014733_updatepaciente")]
    partial class updatepaciente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HJMH.Tarifarios.Shared.Entities.ClasificacionUnicaProcedimientos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CUPS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capitulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cobertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoberturaPlanBeneficiosUPC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionCategoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionGrupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionSubgrupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExcluyeCategoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExcluyeCategoria2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExcluyeGrupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExcluyeSubgrupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncluyeCategoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncluyeCategoria2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncluyeGrupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncluyeSubgrupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueEs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SimultaneoCategoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SimultaneoCategoria2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SimultaneoGrupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SimultaneoSubgrupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subgrupo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CUPS");
                });

            modelBuilder.Entity("HJMH.Tarifarios.Shared.Entities.Homologado", b =>
                {
                    b.Property<int>("CupsId")
                        .HasColumnType("int");

                    b.Property<int>("SoatId")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CupsId", "SoatId");

                    b.HasIndex("SoatId");

                    b.ToTable("Homologados");
                });

            modelBuilder.Entity("HJMH.Tarifarios.Shared.Entities.PacienteEmssanar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barrio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CausaRetiro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CicloVida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoDepartamentoResidencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoGrupoPoblacional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoMunicipioResidencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoMunicipioResidenciaOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionRangoSalarial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionResidencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Edad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaseDatos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FechaFinEfectivaPortabiliadVigente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaInicioEfectivaPortabilidadVigente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaNacimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FichaSisben")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinCobertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrupoEdadUPC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrupoPoblacional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HechoVictimizanteRUV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdAfiliado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdSubsidiado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InicioCobertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalidadComuna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medicamentos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medicina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MunicipioResidencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MunicipioResidenciaOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelSisben")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreIPS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroIdentificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Odontología")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrientacionSexual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrigenAfiliado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrigenEtnico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortabilidadVigente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PuntajeSisben")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PyP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RangoSalarial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistroUnicoVictimas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoFijo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDiscapacidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoIdentificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zona")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PacientesEmssanar");
                });

            modelBuilder.Entity("HJMH.Tarifarios.Shared.Entities.Soat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Articulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capitulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Diferencial")
                        .HasColumnType("real");

                    b.Property<string>("Grupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Paragrafos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("SMLV")
                        .HasColumnType("real");

                    b.Property<string>("Subgrupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("UVB")
                        .HasColumnType("real");

                    b.Property<float>("UVT")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Soat");
                });

            modelBuilder.Entity("HJMH.Tarifarios.Shared.Entities.Homologado", b =>
                {
                    b.HasOne("HJMH.Tarifarios.Shared.Entities.ClasificacionUnicaProcedimientos", "Cups")
                        .WithMany("Homologadores")
                        .HasForeignKey("CupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HJMH.Tarifarios.Shared.Entities.Soat", "Soat")
                        .WithMany("Homologadores")
                        .HasForeignKey("SoatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cups");

                    b.Navigation("Soat");
                });

            modelBuilder.Entity("HJMH.Tarifarios.Shared.Entities.ClasificacionUnicaProcedimientos", b =>
                {
                    b.Navigation("Homologadores");
                });

            modelBuilder.Entity("HJMH.Tarifarios.Shared.Entities.Soat", b =>
                {
                    b.Navigation("Homologadores");
                });
#pragma warning restore 612, 618
        }
    }
}
