// <auto-generated />
using HJMH.Tarifarios.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HJMH.Tarifarios.Backend.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HJMH.Tarifarios.Shared.Entities.ClasificacionUnicaProcedimientos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CUPS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capitulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cobertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoberturaPlanBeneficiosUPC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionCategoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionGrupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionSubgrupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExcluyeCategoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExcluyeCategoria2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExcluyeGrupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExcluyeSubgrupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncluyeCategoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncluyeCategoria2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncluyeGrupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncluyeSubgrupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueEs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SimultaneoCategoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SimultaneoCategoria2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SimultaneoGrupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SimultaneoSubgrupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subgrupo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CUPS");
                });
#pragma warning restore 612, 618
        }
    }
}
